const ANIMAIS = [
  {
    "slug": "gato-mel",
    "categoria": "Gatos",
    "nome": "Gatinho Mel",
    "idade": "1 mês",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 350,00",
    "imagem": "midia/gatos/cat1.jpeg",
    "descricao": "Calmo, carinhoso e apaixonado por colo. Mel é aquele filhote que transforma qualquer cantinho em casa."
  },
  {
    "slug": "gato-rajadinho",
    "categoria": "Gatos",
    "nome": "Rajadinho",
    "idade": "2 meses",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 420,00",
    "imagem": "midia/gatos/cat2.jpeg",
    "descricao": "Curioso e brincalhão, Rajadinho adora explorar e depois dormir enroladinho."
  },
  {
    "slug": "gato-frajolinha",
    "categoria": "Gatos",
    "nome": "Frajolinha",
    "idade": "2 meses",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 390,00",
    "imagem": "midia/gatos/cat3.jpeg",
    "descricao": "Uma pequena aventureira, cheia de personalidade e muito carinho para oferecer."
  },
  {
    "slug": "gato-cinzinha",
    "categoria": "Gatos",
    "nome": "Cinzinha",
    "idade": "3 meses",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 450,00",
    "imagem": "midia/gatos/cat4.jpeg",
    "descricao": "Delicada, tranquila e muito observadora. Uma companhia doce para a rotina."
  },
  {
    "slug": "cao-bidu",
    "categoria": "Cães",
    "nome": "Golden Retriever Bidu",
    "idade": "2 meses",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 2.500,00",
    "imagem": "midia/caes/golden.jpeg",
    "descricao": "Bidu é sociável, alegre e cheio de energia. Um filhote que ama brincar e estar perto de pessoas."
  },
  {
    "slug": "cao-bolota",
    "categoria": "Cães",
    "nome": "Shih Tzu Bolota",
    "idade": "2 meses",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 1.800,00",
    "imagem": "midia/caes/shitzu.jpeg",
    "descricao": "Pequeno no tamanho e enorme na fofura. Bolota é tranquilo e adora atenção."
  },
  {
    "slug": "cao-spitz",
    "categoria": "Cães",
    "nome": "Spitz Alemão Anão",
    "idade": "3 meses",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 2.200,00",
    "imagem": "midia/caes/splitz.jpeg",
    "descricao": "Expressiva, ativa e muito companheira, com uma personalidade impossível de ignorar."
  },
  {
    "slug": "cao-poodle",
    "categoria": "Cães",
    "nome": "Filhote de Poodle Toy",
    "idade": "2 meses",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 1.900,00",
    "imagem": "midia/caes/poodle.jpeg",
    "descricao": "Inteligente, delicada e brincalhona. Uma pequena companhia para grandes aventuras."
  },
  {
    "slug": "ave-pato-mandarim",
    "categoria": "Aves",
    "nome": "Patinho Mandarim",
    "idade": "1 mês",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Registro fictício",
    "preco": "R$ 750,00",
    "imagem": "midia/aves/patinho.jpg",
    "descricao": "Dócil e curioso, o Patinho Mandarim é uma presença alegre e graciosa."
  },
  {
    "slug": "ave-pinguim-pipoca",
    "categoria": "Aves",
    "nome": "Pinguim Mansinho Pipoca",
    "idade": "2 meses",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Registro fictício",
    "preco": "R$ 1.200,00",
    "imagem": "midia/aves/pinguim.jpg",
    "descricao": "Pipoca é o mais tranquilo do grupo e conquista qualquer pessoa com seu jeitinho."
  },
  {
    "slug": "ave-shima-enaga",
    "categoria": "Aves",
    "nome": "Shima Enaga SnowFlakes",
    "idade": "2 meses",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Registro fictício",
    "preco": "R$ 1.500,00",
    "imagem": "midia/aves/fada da neve.webp",
    "descricao": "Pequenina e encantadora, com uma presença delicada e muito especial."
  },
  {
    "slug": "ave-cisne",
    "categoria": "Aves",
    "nome": "Cisne Fofinho",
    "idade": "2 meses",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Registro fictício",
    "preco": "R$ 3.000,00",
    "imagem": "midia/aves/cisne.webp",
    "descricao": "Gracioso e elegante, o Cisne Fofinho é o destaque da coleção de aves."
  },
  {
    "slug": "roedor-zoiudinho",
    "categoria": "Roedores",
    "nome": "Zoiudinho Teddy",
    "idade": "1 mês",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Registro fictício",
    "preco": "R$ 300,00",
    "imagem": "midia/roedores/orelhudo.jpeg",
    "descricao": "Curioso, pequeno e cheio de personalidade. Zoiudinho adora descobrir novidades."
  },
  {
    "slug": "roedor-hamster",
    "categoria": "Roedores",
    "nome": "Hamster Anão Russo",
    "idade": "1 mês",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Registro fictício",
    "preco": "R$ 250,00",
    "imagem": "midia/roedores/hamster.jpeg",
    "descricao": "Pequena, ativa e divertida, perfeita para quem ama observar cada descoberta."
  },
  {
    "slug": "roedor-esquilo",
    "categoria": "Roedores",
    "nome": "Esquilinho Cinza",
    "idade": "2 meses",
    "sexo": "Macho",
    "vacina": "Vacinado",
    "pedigree": "Registro fictício",
    "preco": "R$ 400,00",
    "imagem": "midia/roedores/esquilo.jpeg",
    "descricao": "Ágil e curioso, com muita personalidade e uma energia adorável."
  },
  {
    "slug": "roedor-coelho",
    "categoria": "Roedores",
    "nome": "Mini Coelhinho Lionhead",
    "idade": "2 meses",
    "sexo": "Fêmea",
    "vacina": "Vacinada",
    "pedigree": "Pedigree registrado",
    "preco": "R$ 500,00",
    "imagem": "midia/roedores/coelho.jpeg",
    "descricao": "Um coelhinho delicado, sociável e extremamente fofo. Adora carinho e ambientes tranquilos."
  }
];
